foodieapp/food/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

'''Namespacing is used in Django to prevent conflicts between URL patterns with the 
same name in different applications. By assigning a namespace to each application's 
URLs, you can ensure that the reverse() function and the {% url %} template tag will
always return the correct URL, even if there are multiple URL patterns with the same 
name in different applications.'''
app_name = "food"
urlpatterns = [
    #/
    path('', login_required(views.IndexClassView.as_view()), name='index'),
    #/1
    path("<int:pk>/", login_required(views.FoodDetail.as_view()), name='detail'),
    # add items
    path('add', login_required(views.CreateItem.as_view()), name='create_item'),
    # edit items
    path("update/<int:pk>/", login_required(views.UpdateItem.as_view()), name='update_item'),
    #delete items
    path("delete/<int:item_id>/", login_required(views.delete_item), name='delete_item'),
]

foodieapp/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from users import views as view_form
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("food.urls")),
    path("", include("users.urls")),
    #path("register/", view_form.register, name='register'),
    path("login/", authentication_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", authentication_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodieapp/users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("profile/", views.profilepage, name="profile"),
]

foodieapp/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Item(models.Model):

    def __str__(self):
        return self.item_name
    
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=1,)
    item_name = models.CharField(max_length=100, verbose_name='Item Name')
    item_desc = models.CharField(max_length=200, verbose_name='Item Description')
    item_price = models.IntegerField(verbose_name='Item Price')
    item_image = models.CharField(max_length=500, blank=True, verbose_name='Item Image Link', default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8GV0f6prb-DPesR3lFwG2UsJh94yNz7ijRQ&usqp=CAU')
    
    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})

foodieapp/users/models.py
from django.db import models
from django.contrib.auth.forms import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)
    
    def __str__(self):
        return self.user.username

foodieapp/food/forms.py
'''Importing forms from Django'''
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    '''class Description'''
    class Meta:
        '''class Description'''
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

foodieapp/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

foodieapp/food/views.py
from django.shortcuts import render, redirect

# Create your views here.
from .models import Item
from .forms import ItemForm
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import CreateView
from django.views.generic import UpdateView

'''def index(request):
    item_list = Item.objects.all()
    #a = loader.get_template("food/index.html") 
    context = {
        "item_list": item_list,
    }
    #return HttpResponse(a.render(context, request)) This response is got with loader library.
    return render(request, "food/index.html", context)'''


class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'
    paginate_by = 5
    
    def get_queryset(self):
        # Get the search query from the GET request
        itemname = self.request.GET.get('itemname', '')  # 'item_name' is a common query parameter name (you can change it)

        if itemname:
            # Call your search function to filter the queryset
            item_list = self.model.objects.filter(item_name__icontains=itemname)
        else:
            # Return full queryset if no search query
            item_list = self.model.objects.all()

        return item_list

'''def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        "item" : item,
    }
    return render(request, "food/detail.html", context)'''

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'
    
'''
def create_item(request):
    form = ItemForm(request.POST or None)
    
    if form.is_valid():
        item = form.save()
        return redirect(item.get_absolute_url())

    return render(request, "food/item-form.html", {"form":form})
    '''
    
class CreateItem(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'
    def form_valid(self,form):
        form.instance.user_name = self.request.user
        if not form.cleaned_data['item_image']:
            form.instance.item_image = 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8GV0f6prb-DPesR3lFwG2UsJh94yNz7ijRQ&usqp=CAU'
        return super().form_valid(form)

class UpdateItem(UpdateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-update-form.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['item'] = self.object
        return context
'''
def update_item(request,item_id):
    item = Item.objects.get(id=item_id)
    form = ItemForm(request.POST or None, instance=item)
        
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request, "food/item-form.html", {"form":form, "item":item})
'''

def delete_item(request,item_id):
    item = Item.objects.get(id=item_id)
    
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    return render(request, "food/item-delete.html", { "item" : item })

foodieapp/users/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username.capitalize()}, Your account is created, Now you can Log In to your account.')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, "users/register.html", { "form" : form })

@login_required
def profilepage(request):
    return render(request, "users/profile.html")

foodieapp/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FoodieApp</title>
    <link rel="stylesheet" href="{% static 'food/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-success  bg-primary" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'food:index' %}">FoodApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="justify-content-end" id="navbarNav">
                <ul class="nav nav-tabs justify-content-end">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'food:create_item' %}">Add Item</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Delete Item</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">View Item</a>
                    </li>
                    <li class="nav-item">
                    <form method="POST" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button class="nav-item nav-link" typpe="button">Logout</button>
                    </form>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:profile' %}"><i class="fa-solid fa-user"></i></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-item nav-link" role="button" href="{% url 'login' %}">LogIn</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Sign Up</a>
                    </li>
                {% endif %}
                </ul>
                
            </div>
        </div>
    </nav>
    

    {% block body %}
    {% endblock %}
</body>
</html>

foodieapp/food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}

    <div class="container">
        <div class="row">
            <div class="col-md-7">
                <img src="{{ object.item_image }}" class="card" height="200px" width="100%">
            </div>
            <div class="col-md-5">
                <h1 style="text-align:center"> {{ object.item_name }} </h1>
                <h2 style="text-align:center"> {{ object.item_desc }} </h2>
                <h3 style="text-align:center"> ₹{{ object.item_price }} </h3>
                <h6 style="text-align:center"> This Item is added by : {{ object.user_name }} </h6>
                <a href="{% url 'food:delete_item' object.id %}" class="btn btn-outline-danger">Delete Item</a>
            </div>
        </div>
    </div>
{% endblock %}

foodieapp/food/templates/food/index.html
{% extends 'food/base.html' %}
{% block body %}
    {% include "search.html" %}
    {% for item in item_list %}

    <div class="row">
        <div class="col-md-4 offset-md-2">
            <img class="card" width="75%" height="100px" src="{{ item.item_image }}"/>
        </div>
        <div class="col-md-4">
            <h3> {{ item.item_name }} </h3>
            <h5> {{ item.item_desc }} </h5>
            <h6> ₹{{ item.item_price }} </h6>
        </div>
        <div class="col-md-2">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-info">View Details</a>
        </div>
    </div>

    {% endfor %}
    {% include "pagination.html" with page=page_obj %}
{% endblock %}

foodieapp/food/templates/food/item-delete.html
{% extends 'food/base.html' %}
{% block body %}

<form method="POST">
    {% csrf_token %}
    <h2 class="fs-2 fw-semibold text-center">Are you sure you want to delete {{item.item_name}} </h2>
    <div class="text-center">
        <button type="submit" class="btn btn-warning">Confirm</button>
    </div>
</form>
{% endblock %}

foodieapp/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
{% block body %}
<body style="background-image: url('{% static "users/images/bg_image.jpg" %}'); background-size: cover; background-repeat: no-repeat;">
    <div class="container-fluid justify-content-center">
        <div class="row ">
            <div class="col-sm-8 col-md-6 col-lg-4 offset-md-4 mt-5 mb-5">
                <div class="card shadow rounded-lg mx-auto" style="max-width: 450px;">
                    <div class="card-header bg-info text-white text-center">
                        <div class="card-title my-3">
                            <h5 class="mb-0">Add Item</h5>
                        </div>
                    </div>
                    <div class="card-body text-center px-4">
                        <form method="POST" class="form-group mb-3">
                            {% csrf_token %}
                        <!--    <div class="form-group mb-3">
                                <input type="text" id="item_name" name="item_name" placeholder="Item Name" class="form-control mb-3" required>
                            </div>
                            <div class="form-group mb-3">
                                <input type="text" id="item_desc" name="item_desc" placeholder="Item Description" class="form-control mb-3" required>
                            </div>
                            <div class="form-group mb-3">
                                <input type="number" id="item_price" name="item_price" placeholder="Item Price" class="form-control mb-3" required>                                
                            </div>
                            <div class="form-group mb-3">
                                <input type="text" id="item_image" name="item_image" placeholder="Item Image Link" class="form-control mb-3">
                                
                            </div>
                            {% if form.errors %}
                            <div class="alert alert-warning" role="alert">
                                <ul>{% for field in form %}
                                        {% for error in field.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    {% endfor %}
                                </ul>
                            </div>
                            {% endif %}
                            <button class="btn btn-success" type="submit">Save Item</button>
                        -->
                        {% for field in form %}
                        <div class="form-group mb-3">
                            {{ field.as_p }}
                            <input type="{{ field.field.widget.input_type }}" class="form-control" id="{{ field.id_for_label }}" name="{{ field.name }}" placeholder="{{ field.label }}" {% if field.field.required %} required{% endif %}>
                        </div>
                        {% endfor %}
                        <div class="form-group">
                            <button class="btn btn-outline-primary" type="submit">Save Item</button>
                        </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

foodieapp/food/templates/food/item-update-form.html
{% extends 'food/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
{% block body %}
<body style="background-image: url('{% static "users/images/bg_image.jpg" %}'); background-size: cover; background-repeat: no-repeat;">
    <div class="container-fluid justify-content-center">
        <div class="row ">
            <div class="col-sm-12 col-md-6 col-lg-6 offset-md-3 mt-5 mb-5">
                <div class="card shadow rounded-lg mx-auto" style="max-width: 450px;">
                    <div class="card-header bg-info text-white text-center">
                        <div class="card-title my-3">
                            <h5 class="mb-0">Add Item</h5>
                        </div>
                    </div>
                    <div class="card-body px-4">
                        <form method="POST" class="row g-3 mb-3">
                            {% csrf_token %}
                            {% for field in form %}
                            <div class="col-md-5 mb-3">
                                <strong><label for="floatingInput">{{field.label_tag}}</label></strong>
                            </div>
                            <div class="col-md-7 mb-3">
                                {{ field }}
                                
                            </div>
                            {% endfor %}
                            <div class="form-group text-center">
                                <button class="btn btn-outline-primary" type="submit">Update Item</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
</body>
</html>

foodieapp/food/templates/pagination.html
<nav class="mt-4" aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page=1"><span aria-hidden="true">First</span></a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page.previous_page_number }}"> <span aria-hidden="true">&laquo;</span></a>
        </li>
        {% endif %}
        {% for i in paginator.page_range %}
        <li class="page-item {% if i == page.number %}active{% endif %}">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
        {% endfor %}
        {% if page.has_next %}
        <li class="page-item ">
            <a class="page-link" href="?page={{ page.next_page_number }}"><span aria-hidden="true">&raquo;</span></a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page={{ page.paginator.num_pages }}"><span aria-hidden="true">Last</span></a>
        </li>
            {% endif %}
    </ul>
</nav>

foodieapp/food/templates/search.html
<form action="" method="get">
    <div class="input-group mt-4 mb-5 d-flex justify-content-center">
        <div class="col-md-6">
        <input type="search" name="itemname" id="search_box" class="form-control" list="datalistOptions" placeholder="Type to search...">
        <datalist id="datalistOptions">
            {% for item in item_list %}
            <option value="{{ item.item_name }}">
            {% endfor %}
        </datalist>
        </div>
        <!--<div class="col-md-2">
        <button class="btn btn-outline-info" type="submit" id="button-addon">Search</button>
        </div>-->
    </div>
</form>

foodieapp/users/templates/users/login.html
{% extends 'food/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LogIn</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900&amp;subset=latin,latin-ext'><link rel="stylesheet" href="./style.css">

</head>
{% block body %}
<body style="background-image: url('{% static "users/images/bg_image.jpg" %}'); background-size: cover; background-repeat: no-repeat;">
    
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-6 col-lg-4 offset-md-4 mt-5 mb-5">
                <div class="card mt-5">
                    <div class="card-header bg-info text-white text-center">
                        <div class="card-title">
                            <h5 class="mb-0">Log In</h5>
                        </div>
                    </div>
                    <div class="card-body text-center">
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group mt-1 mb-3">
                                <label for="{{ form.username.id_for_label }}">
                                    {{ form.username.label_tag }}
                                </label>
                                {{ form.username }}
                            </div>
                            <div class="form-group ms-1 mb-3">
                                <label for="{{ form.password.id_for_label }}">
                                    {{ form.password.label_tag }}
                                </label>
                                {{ form.password }}
                            </div>
                            <div class="form-group">
                                <button class="btn btn-outline-primary">Login</button>
                            </div>
                            {% if form.non_field_errors %}
                                <div class="alert alert-danger">{{ form.non_field_errors }}</div>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

</body>
</html>

foodieapp/users/templates/users/logout.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=<device-width>, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    {% block body %}
        <h1>ThankYou for spending your Quality time with FoodieApp,
            <br> You have been logged out of FoodieApp.
            <br> See you soon again.</h1>
            <br>
        <h3> Click Here to <a role="button" href="{% url 'login' %}">Log In </a>again.</h3> 
    {% endblock %}
</body>
</html>

foodieapp/users/templates/users/profile.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
    {% block body %}
    <img height="100px" width="100px" class="img-fluid" src="{{ user.profile.image.url }}">
    <h1>{{ user.username }}</h1>
    {% endblock %}
</body>
</html>

foodieapp/users/templates/users/register.html
{% extends 'food/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registration</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
{% block body %}
<body style="background-image: url('{% static "users/images/background_image.jpeg" %}'); background-size: cover; background-repeat: no-repeat;">
    <div class="container-fluid justify-content-center">
        <div class="row ">
            <div class="col-sm-8 col-md-6 col-lg-4 offset-md-4 mt-5 mb-5">
                <div class="card shadow rounded-lg mx-auto" style="max-width: 450px;">
                    <div class="card-header bg-info text-white text-center">
                        <div class="card-title my-3">
                            <h5 class="mb-0">Register</h5>
                        </div>
                    </div>
                    <div class="card-body text-center px-4">
                        <form method="POST" class="form-group mb-3">
                            {% csrf_token %}
                            <div class="form-group mb-3">
                                <input type="text" id="username" name="username" placeholder="Username" class="form-control mb-3" required>
                            </div>
                            <div class="form-group mb-3">
                                <input type="email" id="email" name="email" placeholder="Email" class="form-control mb-3" required>
                            </div>
                            <div class="form-group mb-3">
                                <input type="password" id="password1" name="password1" placeholder="Password" class="form-control mb-3" required>                                
                            </div>
                            <div class="form-group mb-3">
                                <input type="password" id="password2" name="password2" placeholder="Confirm Password" class="form-control mb-3" required>
                                
                            </div>
                            {% if form.errors %}
                            <div class="alert alert-warning" role="alert">
                                <ul>{% for field in form %}
                                        {% for error in field.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    {% endfor %}
                                </ul>
                            </div>
                            {% endif %}

                            <div class="d-flex justify-content-center mt-4">
                                <p>Already have an account?<a href="{% url 'login' %}" class="text-primary"> LogIn</a></p>
                            </div>
                            <div class="form-group gap-2">
                                <button class="btn btn-outline-info" type="submit">Sign Up</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</body>
{% endblock %}
</html>